routes/web.php
<?php

use App\Http\Livewire\Product\Index;
use App\Http\Livewire\Shop\Cart;
use App\Http\Livewire\Shop\Checkout;
use App\Http\Livewire\Shop\Index as ShopIndex;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/', function () {
    return view('auth.login');
});
Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/admin/product', Index::class)->middleware('auth')->name('admin.product');
// Route::get('/', ShopIndex::class)->name('shop.index');
Route::get('/cart', Cart::class)->name('shop.cart');
Route::get('/checkout', Checkout::class)->name('shop.checkout');

Route::get('/adviselist','App\Http\Controllers\AdviseController@index')->name('advise_list');
Route::get('/faq','App\Http\Controllers\FaqController@index')->name('faq.index');

Route::group(['middleware' => ['auth','preventBackHistory']], function () {
    // Route article
    Route::group([
        'prefix' => 'new',
    ], function(){
        Route::get('/', 'App\Http\Controllers\Admin\News\ArticleController@index')->name('admin.new.list.index');
        Route::get('/edit/{id}', 'App\Http\Controllers\Admin\News\ArticleController@edit')->name('admin.new.edit');
        Route::put('/update/{id}', 'App\Http\Controllers\Admin\News\ArticleController@update')->name('admin.new.update');
        Route::get('/create', 'App\Http\Controllers\Admin\News\ArticleController@create')->name('admin.new.create');
        Route::put('/store', 'App\Http\Controllers\Admin\News\ArticleController@store')->name('admin.new.store');
        Route::get('/detail/{id}', 'App\Http\Controllers\Admin\News\ArticleController@detail')->name('admin.new.detail');
        Route::delete('/delete/{id}', 'App\Http\Controllers\Admin\News\ArticleController@destroy')->name('admin.new.delete');
    });

    Route::get('/menu-config', 'App\Http\Controllers\MenuConfigController@index')->name('admin.menu-config.index');
    Route::group([
        'prefix' => 'master',
    ], function () {
        Route::get('/', 'App\Http\Controllers\Admin\Config\MasterController@index')->name('admin.config.master');
        Route::get('delete/{id}', 'App\Http\Controllers\Admin\Config\MasterController@delete')->name('admin.config.master.delete');
        Route::get('create', 'App\Http\Controllers\Admin\Config\MasterController@create')->name('admin.config.master.create');
        Route::get('edit/{id}', 'App\Http\Controllers\Admin\Config\MasterController@edit')->name('admin.config.master.edit');
        Route::post('insert', 'App\Http\Controllers\Admin\Config\MasterController@insert')->name('admin.config.master.insert');
        Route::post('update', 'App\Http\Controllers\Admin\Config\MasterController@update')->name('admin.config.master.update');
    });

    Route::group([
        'prefix' => 'funds',
    ], function () {
        Route::get('/', 'App\Http\Controllers\FundsController@index')->name('admin.funds');
        Route::get('/create', 'App\Http\Controllers\FundsController@detail')->name('admin.funds.create');
        Route::get('/edit/{id}', 'App\Http\Controllers\FundsController@detail')->name('admin.funds.edit');
        Route::post('/store', 'App\Http\Controllers\FundsController@actionDetail')->name('admin.funds.store');
        Route::put('/update/{id}', 'App\Http\Controllers\FundsController@actionDetail')->name('admin.funds.update');
    });
    Route::group([
        'prefix' => 'fundnews',
    ], function () {
        Route::get('/', 'App\Http\Controllers\FundNewsController@index')->name('admin.fundnews');
        Route::get('/create', 'App\Http\Controllers\FundNewsController@create')->name('admin.fundnews.create');
        Route::get('/edit/{id}', 'App\Http\Controllers\FundNewsController@edit')->name('admin.fundnews.edit');
        Route::get('/download/{id}', 'App\Http\Controllers\FundNewsController@download')->name('admin.fundnews.download');
        Route::put('/update/{id}', 'App\Http\Controllers\FundNewsController@update')->name('admin.fundnews.update');
    });

    Route::group([
        'prefix' => 'fundmaster',
    ], function () {

        Route::get('/', 'App\Http\Controllers\FundMasterController@index')->name('admin.fundmaster');
        Route::get('/create', 'App\Http\Controllers\FundMasterController@detail')->name('admin.fundmaster.create');
        Route::get('/edit/{id}', 'App\Http\Controllers\FundMasterController@detail')->name('admin.fundmaster.edit');
        Route::post('/store', 'App\Http\Controllers\FundMasterController@actionDetail')->name('admin.fundmaster.store');
        Route::put('/update/{id}', 'App\Http\Controllers\FundMasterController@actionDetail')->name('admin.fundmaster.update');
        Route::get('/destroy/{id}', 'App\Http\Controllers\FundMasterController@destroy')->name('admin.fundmaster.destroy');
    });

    Route::group([
        'prefix' => 'fundnav',
    ], function () {

        Route::get('/', 'App\Http\Controllers\FundNAVController@index')->name('admin.fundnav');
        Route::get('/create', 'App\Http\Controllers\FundNAVController@create')->name('admin.fundnav.create');
        Route::get('/edit/{id}', 'App\Http\Controllers\FundNAVController@edit')->name('admin.fundnav.edit');
        Route::post('/store', 'App\Http\Controllers\FundNAVController@store')->name('admin.fundnav.store');
        Route::post('/update/{id}', 'App\Http\Controllers\FundNAVController@update')->name('admin.fundnav.update');
        // Route::get('/destroy/{id}', 'App\Http\Controllers\FundNAVController@destroy')->name('admin.fundnav.destroy');
    });

    Route::group([
        'prefix' => 'recruitment',
    ], function () {
        Route::get('/', 'App\Http\Controllers\RecruitmentController@index')->name('admin.recruitment.index');
    });

    Route::group([
        'prefix' => 'employee',
    ], function () {
        Route::get('/', 'App\Http\Controllers\EmployeeController@index')->name('admin.employee.index');
        Route::get('/create', 'App\Http\Controllers\EmployeeController@create')->name('admin.employee.create');
        Route::get('/edit/{id}', 'App\Http\Controllers\EmployeeController@edit')->name('admin.employee.edit');
        Route::post('/store', 'App\Http\Controllers\EmployeeController@store')->name('admin.employee.store');
        Route::put('/update/{id}', 'App\Http\Controllers\EmployeeController@update')->name('admin.employee.update');
    });


    Route::prefix('nguoiDung')->group(function (){
        Route::get('/create', 'App\Http\Controllers\NguoiDungController@create')->name('nguoiDung.create.index');
        Route::post('/store', 'App\Http\Controllers\NguoiDungController@store')->name('nguoiDung.store');
        Route::get('/{id}/edit', 'App\Http\Controllers\NguoiDungController@edit')->name('nguoiDung.edit.index');
        Route::patch('/{id}', 'App\Http\Controllers\NguoiDungController@update')->name('nguoiDung.update');
        Route::patch('/updateRole', 'App\Http\Controllers\NguoiDungController@updateRole')->name('nguoiDung.update_role');
        Route::get('/', 'App\Http\Controllers\NguoiDungController@index')->name('nguoiDung.index');

    });

    Route::group(['prefix' => 'role'], function() {
        Route::get('/', 'App\Http\Controllers\RoleController@index')->name('roles.index');
        Route::get('/edit/{id}', 'App\Http\Controllers\RoleController@edit')->name('roles.edit');
        Route::get('/create', 'App\Http\Controllers\RoleController@create')->name('roles.create');
        Route::post('/store', 'App\Http\Controllers\RoleController@store')->name('roles.store');
        Route::get('/show/{id}', 'App\Http\Controllers\RoleController@show')->name('roles.show');
        Route::post('/update/{id}', 'App\Http\Controllers\RoleController@update')->name('roles.update');
    });

    Route::group(['prefix' => 'guideline'], function() {
        Route::get('/', 'App\Http\Controllers\GuidelineController@index')->name('guideline.index');
        Route::get('/edit/{id}', 'App\Http\Controllers\GuidelineController@edit')->name('guideline.edit');
        Route::post('/update/{id}', 'App\Http\Controllers\GuidelineController@update')->name('guideline.update');
        Route::get('/create', 'App\Http\Controllers\GuidelineController@edit')->name('guideline.create');
        Route::post('/store', 'App\Http\Controllers\GuidelineController@edit')->name('guideline.store');
        Route::get('/destroy/{id}', 'App\Http\Controllers\GuidelineController@destroy')->name('guideline.destroy');
        Route::get('/detail/{id}', 'App\Http\Controllers\GuidelineController@detail')->name('guideline.detail');
    });

    Route::group(['prefix' => 'survey'], function() {
        Route::get('/', 'App\Http\Controllers\SurveyController@index')->name('survey.index');
        Route::get('/detail/{id}', 'App\Http\Controllers\SurveyController@detail')->name('survey.detail');
    });

    Route::group(['prefix' => 'guideline_detail'], function() {
        // Route::get('/', 'App\Http\Controllers\GuidelineDetailController@index')->name('guideline_detail.index');
        Route::get('/edit/{id}', 'App\Http\Controllers\GuidelineDetailController@edit')->name('guideline_detail.edit');
        Route::patch('/update/{id}', 'App\Http\Controllers\GuidelineDetailController@update')->name('guideline_detail.update');
        Route::get('/create', 'App\Http\Controllers\GuidelineDetailController@create')->name('guideline_detail.create');
        Route::post('/store', 'App\Http\Controllers\GuidelineDetailController@store')->name('guideline_detail.store');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Product extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function getFormatedPriceAttribute()
    {
        return "Rp" . number_format($this->price, 2, ',', '.');
    }

    public function getImageProductAttribute()
    {

        if (is_null($this->image_path)) {
            return 'https://placehold.co/400x225';
        }

        return asset('/storage/'. $this->image_path);
    }

    public function getLastUpdateAttribute()
    {
        return $this->updated_at->diffForHumans();
    }

    public function getShortDescriptionAttribute()
    {
        return Str::limit($this->description, 100, '...');
    }
}

app/Http/Livewire/Admin/Config/Notification/NotificationList.php
<?php

namespace App\Http\Livewire\Admin\Config\Notification;

use App\Enums\ENotificationType;
use App\Enums\EScheduleType;
use App\Enums\ESystemConfigType;
use App\Models\Notification;
use App\Models\SystemConfig;
use Illuminate\Support\Facades\Queue;
use Livewire\Component;

class NotificationList extends Component
{

    public SystemConfig $model;
    public $types;

    public $selectedType;
    public $selectedData;

    protected $listeners = [
        'save-model-event' => 'saveModel'
    ];

    public function mount()
    {
        $this->model = SystemConfig::query()
            ->where('model_name', Notification::class)
            ->where('admin_id', auth()->id())
            ->firstOrNew();

        $this->types = $this->model->content ?? [];

        if (!$this->model->exists) {
            $types = ENotificationType::getList();
            $names = array_flip(ENotificationType::getConstants());

            foreach ($types as $type => $value) {
                $this->types[$type] = [
                    "name" => $names[$type],
                    "via" => [],
                    "remind_before" => 10,
                    "deadline" => date('Y-m-d'),

                ];
            }
        }
    }

    public function render()
    {
        return view('livewire.admin.config.notification.notification-list');
    }

    public function toggleMethod($type, $method, $isActive)
    {
        // dd($type, $method, $isActive);
        $methods = $this->types[$type]['via'] ?? [];
        if ($isActive) {
            $methods[] = $method;
        } else {
            $methods = array_values(array_diff($methods, [$method]));
        }
        $this->types[$type]['via'] = $methods;
    }

    public function saveModel($type = null, $data = null)
    {
        if ($type != null && $data != null) {
            $this->types[$type] = $data;
        }

        $this->model->model_name = Notification::class;
        $this->model->admin_id = auth()->id();
        $this->model->type = ESystemConfigType::NOTIFICATION;
        $this->model->content = ($this->types);
        $this->model->name = 'Notification Configuration';
        $this->model->save();
        $this->dispatchBrowserEvent('show-toast', ['message' => __('notification.common.success.configure'), 'type' => 'success']);

        $this->dispatchBrowserEvent('close-modal-event');
    }
}

app/Http/Livewire/Admin/Config/Notification/NotificationSchedule.php
<?php

namespace App\Http\Livewire\Admin\Config\Notification;

use App\Enums\ENotificationType;
use App\Enums\EScheduleType;
use App\Enums\EWeekDays;
use Carbon\Carbon;
use Exception;
use Livewire\Component;

class NotificationSchedule extends Component
{

    // basic
    public $notificationName;
    public $notificationType;
    public $data;
    public $inGroup2;

    // input fields
    public $remindBefore;
    public $deadline;

    protected function getListeners()
    {
        return [
            ('set-deadline-' . $this->notificationType) => 'setDeadline'
        ];
    }

    protected function rules()
    {
        return [
            'remindBefore' => 'nullable|numeric|min:0',
            'deadline' => 'nullable|date|after:now',
        ];        
    }

    protected function getValidationAttributes()
    {
        return [
            'remindBefore' => __('data_field_name.notification.schedule_remind_before'),
            'deadline' => __('data_field_name.notification.schedule_deadline'),
        ];
    }

    public function mount($notificationType, $data)
    {

        $this->notificationType = $notificationType;
        $this->data = $data;
        $this->notificationName = explode("|", __('data_field_name.notification.type_' . strtolower($data['name'])));
        $this->inGroup2 = ENotificationType::inGroup2($notificationType);

        $this->deadline = $this->data['deadline'] ?? Carbon::now();
        $this->remindBefore = $this->data['remind_before'] ?? 10;
    }

    public function render()
    {
        return view('livewire.admin.config.notification.notification-schedule');
    }

    public function saveSchedule()
    {

        $this->validate();
        $this->data['deadline'] = $this->deadline;
        $this->data['remind_before'] = $this->remindBefore;
        $this->emitUp('save-model-event', $this->notificationType, $this->data);
    }

    public function setDeadline($value) {
        $this->deadline = date('Y-m-d', strtotime($value['deadline-' . $this->notificationType]));
    }
}

app/Http/Livewire/Admin/Employee/EmployeeList.php
<?php

namespace App\Http\Livewire\Admin\Employee;

use App\Http\Livewire\Base\BaseLive;
use App\Models\Employee;
use App\Models\Fund;
use Livewire\Component;
use App\Enums\ECommon;

class EmployeeList extends BaseLive
{
    public $searchName;
    public $searchType;
    public $searchFund;
    public $roles;
    public $dataSortable;
    public function render()
    {
        $query = Employee::query();
        if ($this->searchName) {
            $query->where('fullname', 'like', '%' . trim($this->searchName) . '%');
        }
        if ($this->searchType) {
            $query->where('type', $this->searchType);
        }
        if (!empty($this->searchFund)) {
            if($this->searchFund == -1) {
                $query->whereNull('fund_id');
            } else {
                $query->where('fund_id', $this->searchFund);
            }
        }

        $this->roles = [
            '1' => ECommon::BOARD_OF_DIRECTORS,
            '2' => ECommon::CONTROL_BOARD,
            '3' => ECommon::DIRECTOR_AND_DEPUTY_DIRECTOR,
        ];

        $funds = Fund::all();
        $data = $query->orderBy('priority', 'asc')->paginate($this->perPage);
        if($data->total()>0){
            $arrSortable = $data->toArray();
            $this->dataSortable=$arrSortable['data'];
        }
        return view('livewire.admin.employee.employee-list', [
            'data' => $data,
            'funds' => $funds
        ]);
    }

    public function delete() {
        Employee::findOrFail($this->deleteId)->delete();
        $this->dispatchBrowserEvent('show-toast', ["type" => "success", "message" => "Xóa thành công." ]);
    }
    public function updateOrder($list){
        if($this->searchType){
            foreach ($this->dataSortable as $key_o=> $value_o){
                foreach ($list as $key_n=> $value_n) {
                    if($key_o==$key_n){
                        Employee::where('id',$value_o['id'])->update(['priority'=>$value_n['order']]);
                    }
                }
            }
        }
    }
}

resources/views/livewire/shop/cart.blade.php
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Cart list') }}</div>

                <div class="card-body">
                    <table class="table">
                        <tr class="thead-dark">
                            <th>#</th>
                            <th>Name</th>
                            <th>Price</th>
                            <th>Action</th>
                        </tr>


                        @foreach ($cart['products'] as $product)
                            <tr>
                                <td>{{ $loop->index +1 }}</td>
                                <td>{{ $product->name }}</td>
                                <td>{{ $product->formated_price }}</td>
                                <td>
                                    <button class="btn btn-sm btn-danger" wire:click="removeProductFromCart({{ $product->id }})"><i class="bi bi-trash"></i> Remove</button>
                                </td>
                            </tr>
                        @endforeach
                    </table>
                </div>

                <div class="card-footer">
                    <a class="btn btn-primary float-right" href="{{ route('shop.checkout') }}"><i class="bi bi-cart-fill"></i> Checkout</a>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/livewire/shop/cartnav.blade.php
<div>
    <li class="nav-item">
        <a href="{{ route('shop.cart') }}" class="nav-link"><i class="bi bi-cart4"></i>Cart ({{ $cartTotal }})</a>
    </li>
</div>

resources/views/livewire/shop/checkout.blade.php
<div class="container">
        <div class="card">

            <div class="card-header">
                Checkout Form
            </div>

            <div class="card-body">

                @if ($showFormCheckout)
                <form method="POST" wire:submit.prevent="checkout">
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="firstName">First name</label>
                            <input wire:model="first_name" type="text" class="form-control @error('first_name') is_invalid @enderror" id="firstName" placeholder="" value="" required>
                            @error('first_name')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="lastName">Last name</label>
                            <input wire:model="last_name" type="text" class="form-control @error('last_name') is_invalid @enderror" id="lastName" placeholder="" value="" required>
                            @error('last_name')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="email">Email</label>
                        <input wire:model="email"  type="email" class="form-control @error('email') is_invalid @enderror" id="email" placeholder="acme@example.com">
                        @error('email')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>

                    <div class="mb-3">
                        <label for="address">Address</label>
                        <textarea wire:model="address"  name="address" id="address" class="form-control @error('address') is_invalid @enderror" placeholder="Input address"></textarea>
                        @error('address')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>

                    <div class="row">
                        <div class="col-md-5 mb-3">
                            <label for="city">City</label>
                            <input wire:model="city" type="text" class="form-control @error('city') is_invalid @enderror" id="city">
                            @error('city')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>

                        <div class="col-md-3 mb-3">
                            <label for="postal_code">Postal Code</label>
                            <input wire:model="postal_code" type="text" class="form-control @error('postal_code') is_invalid @enderror" id="postal_code" placeholder="" required>
                            @error('postal_code')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>

                        <div class="col-md-4 mb-3">
                            <label for="phone">Phone</label>
                            <input wire:model="phone" type="text" class="form-control @error('phone') is_invalid @enderror" id="phone" placeholder="+62" required>
                            @error('phone')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                    </div>
                    <hr class="mb-4">

                    <button type="submit" class="btn btn-block btn-outline-primary">Submit</button>
                </form>

                @else
                <button wire:click="$emit('payment', '{{ $snapToken }}')" class="btn btn-primary">Payment</button>

                <script type="text/javascript">
                    window.Livewire.on('payment', function (snapToken) {
                        snap.pay(snapToken, {
                            // Success
                            onSuccess: function (result) {
                                window.livewire.emit('emptyCart')
                                window.location.href = "/"
                            },
                            // Pending
                            onPending: function (result) {
                                location.reload()
                            },
                            // Failed
                            onError: function (result) {
                                location.reload()
                            }
                        })
                    })
                </script>
                @endif
            </div>
        </div>
</div>

resources/views/livewire/shop/index.blade.php
<div class="container">

    <div class="d-flex align-items-center justify-content-end py-2">
        <div class="d-flex">
            <label for="search" class="mr-2">Search</label>
            <input wire:model="search" id="search" type="text" class="form-control" placeholder="keyword">
        </div>
    </div>

    <hr>

    <div class="row">

        @forelse ($products as $product)
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    
                    <img class="card-img-top" src="{{ $product->image_product }}" alt="{{ $product->name }}" srcset="">
                    <div class="card-body">
                        <h5 class="font-weight-bold">{{ $product->name }}</h5>
                        <p class="card-text">{{ $product->short_description }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button wire:click="addToCart({{ $product->id }})" wire:key="{{ $product->id }}" type="button" class="btn btn-sm btn-outline-primary"><i class="bi bi-cart-plus-fill"></i> Add to cart</button>
                            </div>
                            <small class="text-muted">{{ $product->last_update }}</small>
                        </div>
                    </div>
                </div>
            </div>
        @empty
            <div class="row">
                <div class="col-12">
                    <div class="alert alert-primary" role="alert">
                        Produk tidak ditemukan
                    </div>
                </div>
            </div>
        @endforelse
    </div>

    {{ $products->links() }}
</div>